### ISSUE TITLE
Always "Your application is not doing anything right now."

### ISSUE THREAD

**Issue by Cofyc** [uber/go-torch#20]
Hi,

go-torch always show "Your application is not doing anything right now.".

I don't know why. The process I profiled was on high load.

Even if, I run `go tool pprof -dot -lines -seconds 30 http://..../debug/pprof/profile`, I got empty dot file:

```
# go tool pprof -dot -lines -seconds 30 http://localhost:4974//debug/pprof/profile
Fetching profile from http://localhost:4974//debug/pprof/profile?seconds=30
Please wait... (30s)
Saved profile in /root/pprof/pprof.localhost:4974.samples.cpu.001.pb.gz
digraph "unnamed" {
node [style=filled fillcolor="#f8f8f8"]
subgraph cluster_L { L [shape=box fontsize=32 label="Type: cpu\lTime: Jul 28, 2015 at 3:54pm (CST)\lDuration: 30s\l14.40s of 14.40s total (  100%)\l"] }
N1 [label="\n14.40s(100%)" fontsize=24 shape=box tooltip=" (14.40s)"]
}
```

Anyone has this problem? How can I fix it?

**Comment by Cofyc** [comment]
Strangely, I can use `go tool pprof http://localhost:4974//debug/pprof/profile` to profile my program.

**Comment by mgilbir** [comment]
I get the same behaviour on the 1.5 beta 2

**Comment by sandlerben** [comment]
@Cofyc that's strage. It sounds like that could be a bug with `go tool pprof`. Can you try using a different output flag like `-tree` and see if it works?

**Comment by mgilbir** [comment]
FWIW if I read from the binary dump it works just fine

**Comment by sandlerben** [comment]
Since I don't believe this is a bug with go-torch, I am going to close this issue.

**Comment by Cofyc** [comment]
I found the bug.

You can get dot profile from `http://localhost:4974/debug/pprof/profile` but not `http://localhost:4974/debug/pprof/profile`. (Note the slash after the domain!)

With `go-torch`, url should not end with slash (`/`).

```
go-torch --time=30 --file "torch.svg" --url http://localhost:4974 # without slash at the end
```

**Comment by imcom** [comment]
I found that using the entry point does not work for me, I am on Ubuntu 14.10 Go 1.4.2.

However using a dumped profile binary file worked for me ... just let you know, it is a handy tool all in all
