### ISSUE TITLE
Add color to logging

### ISSUE THREAD

**Issue by sandlerben** [uber/go-torch#35]

**Comment by sandlerben** [comment]
@prashantv Before I do this, I had a few questions. Why do we use `fmt.Printf` in some places and `log.Printf` in others? 

I was thinking about creating a very simple `log` type which wraps the `log.XXX` and `fmt.Printf` calls. The `log` wrapper functions would add timestamp and color.

**Comment by prashantv** [comment]
I think the `fmt.Printf` can be removed -- think just the `log.Printf` is all we need.

`torchLog` sounds good to me

**Comment by sandlerben** [comment]
#36
