### ISSUE TITLE
Docker image not available

### ISSUE THREAD

**Issue by titpetric** [uber/go-torch#41]
Docker image cited in README.md is not available.

**Comment by sandlerben** [comment]
@calavera

**Comment by calavera** [comment]
I don't have access to the `uber` user. But you can use the image I built for testing:

https://hub.docker.com/r/calavera/go-torch

It looks like Uber already has an account in Docker Hub, https://hub.docker.com/r/uber, someone should get access and push the image there :smile_cat:

**Comment by sectioneight** [comment]
I'm currently working with Docker Hub support to try to authorize this, since it's not showing up on the web UI. Will close this ticket when the image is successfully pushed to the "uber" Docker org.

**Comment by titpetric** [comment]
Mind also checking if it actually works? I tried building it from the Dockerfile, complains:

~~~
INFO[07:34:30]Run pprof command: go tool pprof -raw -seconds 15 http://10.1.1.2:8080/debug/pprof/profile
FATA[07:34:45]Failed: could not generate flame graph: fork/exec /opt/flamegraph/flamegraph.pl: no such file or directory
~~~

sorry :)

**Comment by sectioneight** [comment]
OK, finally got a build queued: https://hub.docker.com/r/uber/go-torch/

Not sure about the missing perl file though. Ben or @prashantv?

**Comment by titpetric** [comment]
Confirming the issue with it is present also in uber/go-torch on hub:

~~~
root@serenity:~/dev/api-foundations/manuscript/chapter8# ./torch
Unable to find image 'uber/go-torch:latest' locally
latest: Pulling from uber/go-torch
420890c9e918: Already exists
a3ed95caeb02: Already exists
a6999b7fbe20: Already exists
ce12b17e231d: Already exists
f4aed274ecfe: Already exists
28fd3ddc0557: Pull complete
49dfe40fde7f: Pull complete
c4e166ea6286: Pull complete
Digest: sha256:0a4d2ae6d931112b0ffc8dbfe1857711a5f3cd3d4604a348eb105df6dc206de6
Status: Downloaded newer image for uber/go-torch:latest
INFO[09:31:45]Run pprof command: go tool pprof -raw -seconds 15 http://10.1.1.2:8080/debug/pprof/profile
FATA[09:32:00]Failed: could not generate flame graph: fork/exec /opt/flamegraph/flamegraph.pl: no such file or directory
~~~

I can also confirm that flamegraph.pl is in the container:

~~~
root@serenity:~/dev/api-foundations/manuscript/chapter8# docker exec -it pensive_dijkstra ls -la /opt/flamegraph/flamegraph.pl
-rwxr-xr-x    3 root     root         31924 Apr 12 08:01 /opt/flamegraph/flamegraph.pl
~~~

I overrode --entrypoint to run a sleep 10000 command and allow me to get access via exec^. Perl file is not missing, but beyond me why it doesn't work...

**Comment by sandlerben** [comment]
@tianxind I don't have any experience with Docker, and I have no idea why go-torch can't see the flamegraph script. Hopefully Prashant will have a better idea of what is going on.

**Comment by prashantv** [comment]
Looking into this, I think I know why it's saying the flamegraph.pl is not found -- the image is missing perl. I'm adding perl to the image now so that the script can be run.

However, even when that's fixed, `go-torch` currently reads/writes files, which won't work very well from a container. We can use it with a URL and have the SVG written to standard out, but reading files won't really work.

@calavera Is there any solution for reading/writing files on the host filesystem from within the container easily (assuming the host directory has to be mounted?)

**Comment by prashantv** [comment]
This should be working now (after pulling the latest image using `docker pull uber/go-torch`),
```
$ docker run uber/go-torch -t 5 -u http://192.168.64.1:8080 -p > torch.svg
INFO[16:59:53]Run pprof command: go tool pprof -raw -seconds 5 http://192.168.64.1:8080/debug/pprof/profile
INFO[16:59:58]Printing svg to stdout

$ ls -al torch.svg
-rw-r--r--  1 prashant  staff  33741 Apr 12 11:03 torch.svg
```
