### ISSUE TITLE
Support flame graphs for`go test` CPU profiles?

### ISSUE THREAD

**Issue by jim-slattery-rs** [uber/go-torch#45]
Is there any way to generate these beautiful flame graphs for a `cpu.out` file that was created from running tests?
```
go test -cpuprofile cpu.out
```

**Comment by prashantv** [comment]
Yes, go-torch does support creating flame graphs for CPU profiles. There's an example on the README:
https://github.com/uber/go-torch#using-pprof-arguments

Basically, running `go test -cpuprofile cpu.out` will create 2 files:
1. `cpu.out` which is the binary profiling output
2. `[...].test` a test binary which is used to symbolize locations

You then run `go-torch` with the same arguments you would use for pprof: `go-torch main.test cpu.pprof`.

**Comment by jim-slattery-rs** [comment]
Thanks @prashantv for kindly answering my question. I overlooked that section of the README.

**Comment by devoid** [comment]
It looks like there may be an issue here with argument parsing? When I run
`go-torch main.test cpu.pprof` it still attempts to query against localhost's pprof server:
```
INFO[10:45:56]Run pprof command: go tool pprof -raw -seconds 30 http://localhost:8080/debug/pprof/profile
```

If I do: `go-torch --binaryname=main.test -b cpu.pprof` it correctly renders the SVG.

**Comment by prashantv** [comment]
@devoid Are you sure you're using the latest go-torch?

I tried this again and it's working fine for me:
```
> go-torch main.test prof.cpu
INFO[23:40:47] Run pprof command: go tool pprof -raw -seconds 30 main.test prof.cpu
INFO[23:40:47] Writing svg to torch.svg
```

Try getting the latest version,
```
go get -u -f github.com/uber/go-torch
```

**Comment by devoid** [comment]
Hmm for whatever reason `go get` checked out the [commit from April 12th](https://github.com/uber/go-torch/commit/85ad6ad657c83404dcc8e3b9b176f1acb0046dbd). Testing on master now and it works as expected.
