### ISSUE TITLE
parse error using go1.8beta1

### ISSUE THREAD

**Issue by bmizerany** [uber/go-torch#51]
I'm running:

```
go version devel +8fa2344 Sat Jan 7 06:37:46 2017 +0000 darwin/amd64
```

go-torch and FlameGraph are at:

```
$ pwd
/Users/bmizerany/src/github.com/uber/go-torch
$ git rev-parse HEAD
5decf9ecdab5dd3375e1e8d2872351548a7be450
$ cd FlameGraph/
/Users/bmizerany/src/github.com/uber/go-torch/FlameGraph
$ pwd
/Users/bmizerany/src/github.com/uber/go-torch/FlameGraph
$ git rev-parse HEAD
ef645645a3fe814f155e3b6bb6446d1c10c7c2e1
```

I ran a benchmark and then go-torch like:

```
$ go test -run=none -bench=HTTP -memprofile=mem.prof
$ go-torch -alloc_space server.test mem.prof 
```

and got the error:

```
INFO[13:16:41] Run pprof command: go tool pprof -raw -seconds 30 -alloc_space server.test mem.prof
FATA[13:16:41] Failed: could not parse raw pprof output: strconv.ParseInt: parsing "0:": invalid syntax
```

I get the same error with `-alloc_objects`

**Comment by prashantv** [comment]
Thanks for the report @bmizerany 

The parser was initially created for CPU profiles, so it assumed the raw profile output contained 2 columns of output. The memory profile also happened to have 2 columns so it worked fine, but 1.8 adds more columns, breaking the parser.

I'll clean up the parser to parse all columns correctly.

**Comment by bmizerany** [comment]
Ah makes sense. Thank you! I love this tool.

**Comment by bmizerany** [comment]
This is still happening for me with go1.8. I haven't been able to get it working since this fix. Any ideas?

**Comment by prashantv** [comment]
@bmizerany Are you sure you're using the latest version of go-torch?

I'm able to use CPU and memory profiles from go1.8 RC3 fine:
```
$ go version
go version go1.8rc3 darwin/amd64

$ go test -bench . -cpuprofile prof.cpu -memprofile prof.mem
BenchmarkStdUint64-8   	200000000	         9.81 ns/op
BenchmarkUint64-8      	100000000	        13.9 ns/op
PASS
ok  	github.com/uber-go/atomic	4.378s

$ go-torch atomic.test prof.cpu
INFO[23:37:43] Run pprof command: go tool pprof -raw -seconds 30 atomic.test prof.cpu
INFO[23:37:43] Writing svg to torch.svg

$ go-torch atomic.test prof.mem
INFO[23:38:00] Run pprof command: go tool pprof -raw -seconds 30 atomic.test prof.mem
INFO[23:38:00] Writing svg to torch.svg

```

Unfortunately `go-torch` doesn't have a `--version` (Filed #57 since we really should have versions), but you can make sure you have the latest using `go get -u -f github.com/uber/go-torch`

**Comment by bmizerany** [comment]
@prashantv I tried what you suggested but am still getting:

```
$ go get -u -f github.com/uber/go-torch
$ go-torch -alloc_space server.test mem.prof 
INFO[06:00:45] Run pprof command: go tool pprof -raw -seconds 30 -alloc_space server.test mem.prof
FATA[06:00:45] Failed: could not parse raw pprof output: strconv.ParseInt: parsing "0:": invalid syntax
$ cd ~/go/src/github.com/uber/go-torch/
$ git rev-parse HEAD
a4daa2b9d2816627365ca5a4e8cfcd5186ac3659
$ uname -a
Darwin Blakes-MacBook-Pro-2.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
$ go version
go version devel +bd56169 Wed Feb 8 16:20:25 2017 +0000 darwin/amd64
$ 
```

Please let me know if there is more info I can send you.

**Comment by prashantv** [comment]
Can you do `which go-torch` to confirm it's using one built by the `go` tool.

The revision in `~/go/src/github.com/uber/go-torch` looks right, so can you `cd` in, build a binary there, and see if that binary works for parsing the output.
```
$ cd ~/go/src/github.com/uber/go-torch
$ go build .
$ ./go-torch -alloc_space [...]
```

I'm also running on a mac, but I'm using the latest Go 1.8 RC.

**Comment by bmizerany** [comment]
Argh. The move to the new standard `$HOME/go` from `$HOME` keeps haunting me. I was using an old binary. It works now. My bad.

**Comment by prashantv** [comment]
No worries, glad it's working!
