### ISSUE TITLE
malformed location line: runtime.newproc1 /usr/local/Cellar/go/1.9beta2/libexec/src/runtime/proc.go:2987 s=0

### ISSUE THREAD

**Issue by tschottdorf** [uber/go-torch#63]
```
INFO[16:34:03] Run pprof command: go tool pprof -raw -seconds 5 https+insecure://localhost:8080/debug/pprof/profile
FATAL[16:34:08] Failed: could not parse raw pprof output: malformed location line: runtime.newproc1 /usr/local/Cellar/go/1.9beta2/libexec/src/runtime/proc.go:2987 s=0
```

Similar to #61, but not quite the same.

cc @irfansharif ;-)

Attached:

```
go tool pprof -raw -seconds 5 https+insecure://localhost:8080/debug/pprof/profile &> raw.txt
```
[raw.txt](https://github.com/uber/go-torch/files/1150609/raw.txt)

**Comment by irfansharif** [comment]
is there a document somewhere with pprof's output grammar definition? only thing I could find was https://github.com/gperftools/gperftools/blob/855b3800064db49af823b85a54be269923eb6f4d/docs/cpuprofile-fileformat.html but at first glance it seems out of date (2007).

**Comment by tschottdorf** [comment]
I think https://github.com/google/pprof/blob/master/profile/profile.go#L431 is the best you're gonna get - note also that this points out that the raw format is "mainly for debug purposes". It may be the wrong format to ingest in the first place since it can probably change without notice and then it really matters which `pprof` version you run...

**Comment by tschottdorf** [comment]
The `-proto` flag *seems* more appropriate. See https://github.com/google/pprof/blob/master/profile/profile.go#L299 and https://github.com/google/pprof/blob/master/proto/profile.proto. But.. that's more work than just patching the raw format, except we wouldn't have to do it again over and over. @prashantv any reason for using the `-raw` format over others in the first place?

**Comment by sandlerben** [comment]
When I first wrote go-torch, the tool actually ingested the DOT graph output and did some processing on it. 

From what I remember, this led to unexpected behavior sometimes, so Prashant simplified it by ingesting the raw output (see #29). I'm all for reading from the proto, @tschottdorf can you make an issue and I'll look into how feasible that would be?

**Comment by irfansharif** [comment]
@sandlerben: #64.

**Comment by tschottdorf** [comment]
Poked a bit more. The case here is basically multi-line output for locations:

https://github.com/google/pprof/blob/master/profile/profile.go#L508

This is going to be awkward to parse. #64 sounds like the right solution.
